import localFont from "next/font/local";
import "./globals.css";

const oranienbaum = localFont({
src: "./fonts/Oranienbaum-Regular.woff",
variable:"--regular",
});

const playfairDisplay = localFont({
  src: "./fonts/PlayfairDisplay-Italic.woff",
  variable:"--italic",
})

export const metadata = {
  title: "Good Food - Nutritional Advisor and Private Chef Service",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${oranienbaum.variable} ${playfairDisplay.variable}`}>
        {children}
      </body>
    </html>
  );
}
